// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-blog/internal/dao/internal"
)

// internalCommentsDao is an internal type for wrapping the internal DAO implementation.
type internalCommentsDao = *internal.CommentsDao

// commentsDao is the data access object for the table comments.
// You can define custom methods on it to extend its functionality as needed.
type commentsDao struct {
	internalCommentsDao
}

var (
	// Comments is a globally accessible object for table comments operations.
	Comments = commentsDao{
		internal.NewCommentsDao(),
	}
)

// Add your custom methods and functionality below.
