// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-blog/internal/dao/internal"
)

// internalLogsDao is an internal type for wrapping the internal DAO implementation.
type internalLogsDao = *internal.LogsDao

// logsDao is the data access object for the table logs.
// You can define custom methods on it to extend its functionality as needed.
type logsDao struct {
	internalLogsDao
}

var (
	// Logs is a globally accessible object for table logs operations.
	Logs = logsDao{
		internal.NewLogsDao(),
	}
)

// Add your custom methods and functionality below.
