// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-blog/internal/dao/internal"
)

// internalPostTagsDao is an internal type for wrapping the internal DAO implementation.
type internalPostTagsDao = *internal.PostTagsDao

// postTagsDao is the data access object for the table post_tags.
// You can define custom methods on it to extend its functionality as needed.
type postTagsDao struct {
	internalPostTagsDao
}

var (
	// PostTags is a globally accessible object for table post_tags operations.
	PostTags = postTagsDao{
		internal.NewPostTagsDao(),
	}
)

// Add your custom methods and functionality below.
