// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-blog/internal/dao/internal"
)

// internalPostsDao is an internal type for wrapping the internal DAO implementation.
type internalPostsDao = *internal.PostsDao

// postsDao is the data access object for the table posts.
// You can define custom methods on it to extend its functionality as needed.
type postsDao struct {
	internalPostsDao
}

var (
	// Posts is a globally accessible object for table posts operations.
	Posts = postsDao{
		internal.NewPostsDao(),
	}
)

// Add your custom methods and functionality below.
