// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-blog/internal/dao/internal"
)

// internalRolePermissionsDao is an internal type for wrapping the internal DAO implementation.
type internalRolePermissionsDao = *internal.RolePermissionsDao

// rolePermissionsDao is the data access object for the table role_permissions.
// You can define custom methods on it to extend its functionality as needed.
type rolePermissionsDao struct {
	internalRolePermissionsDao
}

var (
	// RolePermissions is a globally accessible object for table role_permissions operations.
	RolePermissions = rolePermissionsDao{
		internal.NewRolePermissionsDao(),
	}
)

// Add your custom methods and functionality below.
