// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-blog/internal/dao/internal"
)

// internalUserRolesDao is an internal type for wrapping the internal DAO implementation.
type internalUserRolesDao = *internal.UserRolesDao

// userRolesDao is the data access object for the table user_roles.
// You can define custom methods on it to extend its functionality as needed.
type userRolesDao struct {
	internalUserRolesDao
}

var (
	// UserRoles is a globally accessible object for table user_roles operations.
	UserRoles = userRolesDao{
		internal.NewUserRolesDao(),
	}
)

// Add your custom methods and functionality below.
